### ISSUE TITLE
Errror on Runing npm start

### ISSUE THREAD

**Issue by katienoj** [dan-divy/spruce#67]
I have setup the application but am getting the below error when i run npm start.

> spruce@4.0.0 start C:\Users\Admin\Desktop\spruce-master
> node update.js; node ./bin/www

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\Admin\Desktop\spruce-master\update.js;'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spruce@4.0.0 start: `node update.js; node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spruce@4.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by katienoj** [comment]
Apparently When I use RUN using command >>>>` node ./bin/www` it starts correctly. Any help?
